#!/bin/bash
#   IMPORTANT BUGS:
#  1.       Ubuntu-Tweak has a repository to get added ..
#  2.       Google-Chrome doesn't get to install ..
#  3.       Added Repositories has to be removed at the end ..
#  4.       Installations & Upgrades has to be forced ( -y option ) ..
#  5.       Code has to be cleaned & highly refactored & commented ..
#  6.       The Script needs to check if the wanting-to-tweak file is already tweaked ..
#  7.       The Script lacks file configuration tweaks ( except for one, which is pretty lame ) ..
#  This is the main Script for preparing Linux Systems for Use after a Fresh Install !
#  This script will be used to invoke the other ones
[[ $EUID == 0 ]] || { echo 'Please run this script as root';exit 1; }
declare BITS=$([[ "$(uname -i)" == 'x86_64' ]] && echo true || echo false);clear
# declaring functions
function IsYes {
	d="$1";if [[ "${d:0:1}" == 'y' ]] && [[  "${#d}" -le 4 ]];then return 0; else return 1;fi
}
function Verified {
	if ! $choice;then
		return 0
	else
		read -p "Do you want to install $1 ? [Y/N]: " cff
		if IsYes "${cff=yes}";then notify-send "Installing $1 ..";return 0; else notify-send "Aborting $1 .."; return 1;fi
	fi
}
function finalize {
	if [ -n "$1" ];then notify-send "Work Done with $1 ..";fi;sudo dpkg --configure -a;sudo apt-get autoclean;sudo apt-get autoremove
	clear;sudo apt-get install -f;clear;axel &>/dev/null
}
##################################################################### Talking with the User ###############################################
cd "${0%/*}";read -p "Congratulations for Installing $(lsb_release -ds)"'!';clear
printf "What do you want ?\n\t1. To Get Prompted before each (non-important) installation ..\n\t2. To Just Install everything quietly ..\n\tPS: Accept is given to any skipped prompt .. and remember:\n\t\tIf you want to skip anything, just use (ctrl-c) ;)\n\t"
read -p 'The Number of your choice is: ' choice;echo "Checking Internet Connection .."
if ! sudo add-apt-repository ppa:linrunner/tlp -y &>/dev/null;then
        echo 'Unable to Connect to Internet or either slow speed';exit 1
fi;echo 'Established an Internet Connection !';sleep 3;clear
choice=$([[ $choice == 1 ]] && echo true || echo false)
notify-send 'Updating Cache ..';sudo apt-get update
sudo dpkg --configure -a
#finalize
#  1: Install Important Utitilites
	sudo apt-get remove --purge fglrx fglrx_* fglrx-amdcccle* fglrx-dev* &>/dev/null
	sudo rm /etc/X11/xorg.conf &>/dev/null
	# sudo apt-get install --reinstall xserver-xorg-core xserver-xorg-video-intel libgl1-mesa-glx \
 #              libgl1-mesa-dri libgl1-mesa-glx:i386 libgl1-mesa-dri:i386 -y
	sudo dpkg-reconfigure xserver-xorg;clear
	sudo service apport stop ; sudo sed -ibak -e s/^enabled\=1$/enabled\=0/ /etc/default/apport
              sudo apt-get install axel curl lynx build-essential cdbs fakeroot dh-make debhelper debconf libstdc++6 gconf-editor -y zenity
	# swap optimization
	fd="$HOME/Desktop/test.$RANDOM";fd2="$HOME/Desktop/tester.$RANDOM"
	echo '# Decrease swap usage to a workable level' > "$fd"
	echo 'vm.swappiness=10' >> "$fd"
	echo '# Improve cache management' >> "$fd"
	echo 'vm.vfs_cache_pressure=50' >> "$fd"
	cat '/etc/sysctl.conf' "$fd" > "$fd2"
	sudo mv -f "$fd2" '/etc/sysctl.conf'
	sudo sed -i 's@exit 0@/sbin/iwconfig wlan0 power off;exit 0@' '/etc/pm/power.d/wireless'
	rm "$fd";rm "$fd2"
	finalize
if [[ ! -r "$HOME/.config/SUDO_ASKPASS" ]];then
    echo '#!/bin/bash' > "$HOME/.config/SUDO_ASKPASS"
    echo 'zenity --password --title="Password Prompt"' >> "$HOME/.config/SUDO_ASKPASS"
fi
finalize
sudo apt-get install ubuntu-restricted-extras dkms libqtgui4 wget execstack -y
sudo apt-get install libelfg0 dh-modaliases linux-headers-generic xserver-xorg-core mesa-utils mesa-utils-extra -y
finalize
sudo apt-get install libgcc1 lib32z1 lib32gcc1 libc6-i386 fancontrol preload realpath git flashplugin-installer bum -y
cd /etc/xdg/autostart/;sudo sed -i 's/NoDisplay=true/NoDisplay=false/g' *.desktop;cd -
finalize
#  2: Install Sublime-Text
if Verified 'Sublime Text';then
	sudo bash subl_install
fi
finalize 'Sublime Text'
#  3: Install Google-Chrome
google-chrome &>/dev/null # checking if it is already installed
if [[ $? -eq 127 ]];then # proceeding only if it isn't installed
	if Verified 'Google Chrome';then
		sudo apt-get install libxss1 # needed library ..
		name="$HOME/Downloads/Google_Chrome_$RANDOM.deb"
		echo 'Downloading Google Chrome ..';mkdir -p "$HOME/Desktop/Temp/Google_Chrome"; cd "$HOME/Desktop/Temp/Google_Chrome"
		if $BITS;then wget -v 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
		else wget -v 'https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb'; fi
		sudo dpkg -i google-chrome*
		sudo rm "$name"
		
	fi
fi
#  4: Install VLC
if Verified 'install VLC';then sudo apt-get install vlc;fi
finalize 'VLC'
#  5: Unity & Ubuntu Tweaks
if Verified 'install Unity Tweak'; then sudo apt-get install unity-tweak-tool -y;fi
if Verified 'install Ubuntu Tweak'; then sudo apt-get install ubuntu-tweak -y;fi
finalize 'Tweaks'
#  6: Java & Eclipse
if Verified 'install Eclipse (C/C++)';then sudo apt-get install eclipse-cdt -y # because the jdk is going to be installed anyway with eclipse
elif Verified 'install Java'; then
	typ='jdk';if $choice;then read -p 'Jdk or Jre ? ' typ;typ="$(echo $typ | tr [[:upper:]] [[:lower:]])";fi
	sudo apt-get default-$typ
fi
finalize 'Java'
#  7: Update & Finish
sudo apt-get update && sudo apt-get upgrade
finalize;notify-send 'Done Preparing '"$(lsb_release -is)"' !'
#  8: Hardware Improvements
if Verified 'use Tlp (Improves Battery Life)';then
	
	sudo apt-get update
	sudo apt-get install tlp tlp-rdw -y
	sudo tlp start
fi
sudo apt-get upgrade;sudo apt-get dist-upgrade
#  9: Reboot
# notify-send 'Rebooting after 10 seconds ..'
# sleep 10
# sudo reboot
