#!/bin/bash
#   IMPORTANT BUG:
#       1. We need a narrower view for the user needs (ex. a web developer might get eclipse for c/c++ installed,
#                       beause he is still considered a "programmer")
#       2. Code needs to be tested ..
#  This is the main Script for preparing Linux Systems for Use after a Fresh Install !
[[ $EUID == 0 ]] || { echo 'Please run this script as root';exit 1; }
if [[ -z "$(which aptitude)" ]] || [[ -z "$(which dpkg)" ]];then
    echo 'This script is (currently) meant to run only on debian-based systems with the aptitude package manager ..'
    exit 1
fi

function clean {
    [[ -z "$1" ]] || notify-send "Work Done with $1 .."
    sudo dpkg --configure -a
    sudo aptitude clean --full-resolver
    sudo aptitude autoclean --purge-unused
}
###### checking needed applications
clean ; clear
for application in 'uname' 'wget' 'notify-send' 'lsb_release' 'which' 'add-apt-repository' 'mktemp'\
'bash' 'sleep' 'ping' 'sed' 'service' 'swapoff' 'swapon' 'grep' 'egrep' 'printf';do
    if [[ -z "$(which "$application")" ]];then
        echo "Installing $application ( needed to run the script ) .."
        sudo aptitude install "$application" || { echo "$application failed to install .."; exit 1; }
    fi
done
cd "${0%/*}" ; clear
echo "Congratulations for Installing $(lsb_release -ds)"'!' ; sleep 3 ; clear
declare -r BITS64=$([[ "$(uname -i)" == 'x86_64' ]] && echo true || echo false) ; clear

function Verified {
    $CHOICE || return 0
    $2 || return 1
    if [[ -n "$3" ]];then
        if [[ -n "$(which "$3")" ]];then
            notify-send "$1 was found to be already installed .."
            return 1
        fi
    fi
    if IsYes -p "Do you want to install $1 ? [Y/N]: ";then
        notify-send "Installing $1 .."
        return 0
    else
        notify-send "Aborting $1 .."
        return 1
    fi
}

echo 'Checking Internet Connection ..'
ping -c3 'www.google.com' &>/dev/null || { echo 'Unable to Connect to Internet or either slow speed';exit 1; }
sleep 2 ; clear
############################################ STARTING WORK ###############################
declare PROGRAMMER=false DESIGNER=false WEBDEV=false
until [[ "$user_type" -le 5 ]] && [[ -n "$user_type" ]];do
    clear
    printf "What do you happen to often use Software for ?\n\t1. Programming\n\t2. Graphics Design\n\t\
3. The first Two ( includes web design ) ..\n\t\n\t4. Web Development .. \n\t5. Typical Computing ..\n\t"
    read -p 'The Number of your choice is: ' user_type
done
case "$user_type" in
    1 ) PROGRAMMER=true;;
    2 ) DESIGNER=true;;
    3 ) PROGRAMMER=true ; DESIGNER=true;;
    4 ) WEBDEV=true ; PROGRAMMER=true;;
esac
declare -r PROGRAMMER DESIGNER WEBDEV

until [[ "$CHOICE" -le 2 ]] && [[ -n "$CHOICE" ]];do
    clear
    printf "What do you want ?\n\t1. To Get Prompted before each major installation ..\n\t\
2. To Just Install everything quietly ..\n\tPS: Accept is given to any skipped prompt .. and remember:\n\t\t\
If you want to skip anything, just use (ctrl-c) ;)\n\t"
    read -p 'The Number of your choice is: ' CHOICE
done ; declare -r CHOICE=$([[ $CHOICE == 1 ]] && echo true || echo false)
notify-send 'Updating Cache ..' ; sudo aptitude update ; clean

sudo rm /etc/X11/xorg.conf &>/dev/null
sudo aptitude reinstall -y xserver-xorg-core xserver-xorg-video-intel libgl1-mesa-glx\
libgl1-mesa-dri libgl1-mesa-glx:i386 libgl1-mesa-dri:i386 curl lynx build-essential cdbs libxss1\
ubuntu-restricted-extras dkms libqtgui4 wget execstack fakeroot dh-make debhelper debconf\
libstdc++6 gconf-editor zenity libelfg0 dh-modaliases linux-headers-generic xserver-xorg-core mesa-utils\
mesa-utils-extra install libgcc1 lib32z1 lib32gcc1 libc6-i386 fancontrol preload realpath git flashplugin-installer bum 2>/dev/null
sudo dpkg-reconfigure xserver-xorg
sudo service apport stop
sudo sed -ibak -e s/^enabled\=1$/enabled\=0/ /etc/default/apport

if ! egrep 'vm.swappiness=[0-9]{1,2}' '/etc/sysctl.conf' ||
    ! egrep 'vm.vfs_cache_pressure=[0-9]{1,2}' '/etc/sysctl.conf';then
        echo '# Decrease swap usage to a workable level' >> '/etc/sysctl.conf'
        echo 'vm.swappiness=10' >> '/etc/sysctl.conf'
        echo '# Improve cache management' >> '/etc/sysctl.conf'
        echo 'vm.vfs_cache_pressure=50' >> '/etc/sysctl.conf'
        sudo sed -i 's@exit 0@/sbin/iwconfig wlan0 power off;exit 0@' '/etc/pm/power.d/wireless'
        rm "$fd";rm "$fd2" ; clean
        swapoff -a ; swapon -a
fi

if egrep "$HOME/.bashrc" 'SUDO_ASKPASS=';then
    echo '#!/bin/bash' > "$HOME/.config/SUDO_ASKPASS"
    echo 'zenity --password --title="Password Prompt"' >> "$HOME/.config/SUDO_ASKPASS"
    echo 'SUDO_ASKPASS="$HOME/.config/SUDO_ASKPASS"' >> "$HOME/.bashrc"
fi

cd /etc/xdg/autostart/ ; sudo sed -i 's/NoDisplay=true/NoDisplay=false/g' *.desktop ; cd -

if Verified 'Sublime Text (Sophisticated Text Editor)' $PROGRAMMER subl;then
    sudo bash subl_install ; clean 'Sublime Text'
fi

if Verified 'Google Chrome' true google-chrome;then
    sudo aptitude install -y libxss1 &>/dev/null
    echo 'Downloading Google Chrome ..'
    temp_dir="$(mktemp -d)" ; cd "$temp_dir"
    site="https://dl.google.com/linux/direct/google-chrome-stable_current_$($BITS64&&echo 'amd64'||echo 'i386').deb"
    wget -v "$site" -o "chrome.deb"
    sudo dpkg -i 'chrome.deb'
    cd - ; rm -r "$temp_dir"
fi

if Verified 'VLC' true vlc;then
    sudo aptitude install vlc -y ; clean 'VLC'
fi

if Verified 'Unity Tweak' true unity-tweak-tool;then
    sudo aptitude install unity-tweak-tool -y ; clean
fi

if Verified 'Eclipse (C/C++)' $PROGRAMMER eclipse;then
    sudo aptitude install eclipse-cdt -y # because the jdk is going to be installed anyway with eclipse
elif Verified 'Eclipse (Classic)' $PROGRAMMER eclipse;then
    sudo aptitude install eclipse -y
elif Verified 'Java' java; then
    if $CHOICE;then
        until echo "$typ" | egrep -qi '^j(dk|re)$';do
            read -p 'Jdk or Jre ? ' typ
        done
    else
        typ="$($PROGRAMMER&&echo 'jdk' || echo 'jre')"
    fi
    sudo aptitude install default-"$(echo "$typ" | tr [[:upper:]] [[:lower:]])" -y
fi ; clean 'Java'

if Verified 'Gimp' gimp $DESIGNER;then
    sudo aptitude install gimp -y
fi
if Verified 'LAMP Bundle (MySQL - PHP - Apache)'; then
    sudo bash lamp_install
fi
if Verified 'Valgrind & Valkyrie (C/C++ Debugger)' $PROGRAMMER;then # inconsistent, bec it isn't suitable for a web developer ..
    sudo bash valgrind_install -q
fi
if Verified 'Tlp (battery life & heat improvement)' tlp-rdw;then
    sudo add-apt-repository ppa:linrunner/tlp -y
    sudo aptitude update
    sudo aptitude install tlp*
    sudo add-apt-repository ppa:linrunner/tlp -ry
fi

notify-send 'Rebooting after 10 seconds ..'
sudo aptitude update
sudo aptitude dist-upgrade -y
sudo aptitude full-uprade -y
sleep 10 ; sudo reboot
